# Generated by Django 3.2.4 on 2021-07-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0002_auto_20210701_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='bank',
            field=models.CharField(default='BizAppDev Systems', max_length=25),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp601', max_length=70),
        ),
        migrations.AlterField(
            model_name='employee',
            name='language',
            field=models.CharField(choices=[('english', 'ENGLISH'), ('gujarati', 'GUJARATI'), ('hindi', 'HINDI'), ('marathi', 'MARATHI')], default='english', max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nuban',
            field=models.CharField(default='Employee', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
